### ISSUE TITLE
您好可以留下您的邮箱嘛？有个问题要请教

### ISSUE THREAD

**Issue by Richrain** [shispt/dht#2]
您好可以留下您的邮箱嘛？有个问题要请教 
python版本 与redis的版本是？
最后瞻仰一下作者大神，期待回复

**Comment by shispt** [comment]
我python本地是2.7.6，3.* 没测过；redis 2.*,3.*应该都可以，只用了几个最基本的命令

**Comment by Richrain** [comment]
谢谢
